name: codspeed-benchmarks

on:
  # Run on pushes to the main branch
  push:
    branches:
      - "main"
  # Run on pull requests
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  benchmarks:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # - name: Install env dependencies
      #   run: sudo DEBIAN_FRONTEND=noninteractive apt-get -yq install python3-dev libxml2-dev libxslt-dev

      - run: sudo DEBIAN_FRONTEND=noninteractive apt-get -yq install libpython3.10-dev

      # - run: export C_INCLUDE_PATH=/usr/include/python3.10:$C_INCLUDE_PATH
      # - run: export C_INCLUDE_PATH=/home/haoshan/repos_eagi/benchmarking/fork/actions-runner/_work/_tool/Python/3.10.13/x64/include/python3.10:$C_INCLUDE_PATH
      - run: export CPLUS_INCLUDE_PATH="$CPLUS_INCLUDE_PATH:/home/haoshan/repos_eagi/benchmarking/fork/actions-runner/_work/_tool/Python/3.10.13/x64/include/python3.10"

      - name: Install local version of pytest-codspeed
        run: git clone https://github.com/haoshan98/pytest-codspeed.git && cd pytest-codspeed && pip install . & cd ../

      - name: Install project dependencies
        run: pip install -e .
        
      - name: Run benchmarks
        uses: CodSpeedHQ/action@main
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: pytest tests/kernels/test_layernorm.py --codspeed



      # # - uses: actions/checkout@v4

      # # - uses: pdm-project/setup-pdm@v3
      # #   with:
      # #     python-version: "3.10"
      # #     cache: true

      # # - name: install deps
      # #   run: |
      # #     pdm venv create --with-pip --force $PYTHON
      # #     pdm install -G testing -G testing-extra -G email

      # # - name: Run CodSpeed benchmarks
      # #   uses: CodSpeedHQ/action@v2
      # #   with:
      # #     run: pdm run pytest ./kernels/test_layernorm.py --codspeed

      # - uses: actions/checkout@v4

      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.10"

      # # - name: cuda-toolkit
      # #   uses: Jimver/cuda-toolkit@v0.2.11
      # #   with:
      # #     cuda: "12.1.0"

      # # - run: echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"
      # # - run: echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
      # # - run: nvcc -V

      # - name: Install project dependencies
      #   run: pip install -e . && pip install pytest && pip install pytest-codspeed

      # - name: Get codspeed-runner
      #   run: curl -I -fsSL -w "%{http_code}" -o /dev/null https://github.com/CodSpeedHQ/runner/releases/download/v2.0.2/codspeed-runner-installer.sh

      # # - name: check
      # #   run: vim /usr/bin/ldd
      # - name: Install codspeed-runner
      #   run: curl -fsSL https://github.com/CodSpeedHQ/runner/releases/download/v2.0.2/codspeed-runner-installer.sh | bash -s -- --quiet

      # - name: Activate codspeed-runner
      #   run: source "$HOME/.cargo/env"

      # - name: Run pytest
      #   # run: bash codspeed_action.sh
      #   run: pytest tests/kernels/test_layernorm.py --codspeed

      # - name: Run benchmarks
      #   # run: bash codspeed_action.sh
      #   run: CODSPEED_LOG=debug codspeed-runner --token be5d5cd5-e053-4b63-8c53-8c95cc84e907 -- 'pytest tests/kernels/test_layernorm.py --codspeed'

      # # - name: Run benchmarks
      # #   # uses: CodSpeedHQ/action@v2
      # #   uses: CodSpeedHQ/action@v2.0.2
      # #   # uses: CodSpeedHQ/action@v1
      # #   with:
      # #     token: ${{ secrets.CODSPEED_TOKEN }}
      # #     run: pytest tests/kernels/test_layernorm.py --codspeed
